export interface IProduct {
    
jobTitle: String,
  jobType: String,
  jobIndustry: String,
  salaryType: String,
  salary: Number,
  startDate: Date,
  endDate: Date,
  startTime: String,
  endTime: String,
  totalHours: Number,
  jobExpiration: String,
  requiredNumber: Number,
  workPeriod: String,
  workRegion: String,
  location: String,
  description: String,
  jobRole: String,
  requirement: String,
  selfEmployer: Boolean,
  companyName: String,
  companyWebsite: String,
  employerName: String,
  employerEmail: String,
  employerPhone: String,
  coverImage: String,
  featuredImages: String,
  employerId: String,
}